### ISSUE TITLE
Home Page布局需求说明

### ISSUE THREAD

**Issue by xiaohou77** [elastos/Elastos.App.Wallet.Elephant.iOS#27]

**Comment by xiaohou77** [comment]
![1541543547899_ pic_hd](https://user-images.githubusercontent.com/38149053/49275928-db493280-f4b7-11e8-89af-fcf9d6b21901.jpg)

**Comment by xiaohou77** [comment]
![1521543547803_ pic](https://user-images.githubusercontent.com/38149053/49276018-22372800-f4b8-11e8-8155-1d3da530cb2c.jpg)

**Comment by xiaohou77** [comment]
@xuxinlai2002 还有俩个小效果（轻微的阴影效果）没有实现，看截图哈：
![image](https://user-images.githubusercontent.com/38149053/49364096-5ad83b00-f71e-11e8-8202-992de1a18a79.png)

**Comment by xuxinlai2002** [comment]
麻烦再确认一下。

**Comment by xiaohou77** [comment]
谢谢xinlai的修改，设计设厉害的双眼又发现了几个细节哈，麻烦帮忙再改下
![image](https://user-images.githubusercontent.com/38149053/49492055-ab23da00-f891-11e8-8acf-6e564008e3da.png)
![image](https://user-images.githubusercontent.com/38149053/49492096-ddcdd280-f891-11e8-9f09-feb3c186f873.png)

**Comment by xuliting** [comment]
问题迁移
