### ISSUE TITLE
主页滑动时不显示我的资产，只留标题My Wallet

### ISSUE THREAD

**Issue by xiaohou77** [elastos/Elastos.App.Wallet.Elephant.iOS#29]
![image](https://user-images.githubusercontent.com/38149053/49357682-fa8bce00-f70a-11e8-9703-8113a338cbb7.png)

**Comment by xiaohou77** [comment]
@xuxinlai2002 @xuliting 这个下周的版本是否可以fix下？算是一个基本的可用性问题，资产多的时候滑动屏幕上面被遮住，用户会感觉难受。
或者明天例会大家讨论下一起

**Comment by xuliting** [comment]
问题迁移
